### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by neonoafs** [XLuma/SV-Randomizer#15]
Im getting the error below:

```
Requirement already satisfied: fnvhash in c:\users\neono\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (0.1.0)
Traceback (most recent call last):
  File "C:\Users\neono\Downloads\SV-Randomizer-master\Randomizer.py", line 3, in <module>
    import Randomizer.WildEncounters.wildrando as WildRandomizer
  File "C:\Users\neono\Downloads\SV-Randomizer-master\Randomizer\WildEncounters\wildrando.py", line 66
    match index:
          ^
SyntaxError: invalid syntax
```

My config is:

```
`{
    "wild_randomizer": {
        "is_enabled": "yes",
        "exclude_legendaries": "no"
    },
    "trainer_randomizer": {
        "is_enabled": "yes",
        "force_6_pokemons_on_important_trainers": "yes",
        "force_perfect_ivs": "yes",
        "make_ai_smart_for_all_trainers": "yes",
        "allow_all_trainers_to_terastalize": "yes",
        "randomize_fixed_tera_type": "yes",
        "randomize_all_tera_type": "yes"
    },
    "personal_data_randomizer": {
        "is_enabled": "yes",
        "randomize_abilities": "yes",
        "ban_wonder_guard": "no",
        "randomize_movesets": "yes",
        "randomize_evolutions": "yes"
    },
    "starter_randomizer": {
        "is_enabled": "yes",
        "randomize_all_gifts": "yes",
        "randomize_tera_type": "yes",
        "show_starters_in_overworld": "yes"
    },
    "static_randomizer": {
        "is_enabled": "no",
        "randomize_tera_type_for_static_tera": "no"
    },
    "tm_randomizer": {
        "is_enabled": "no"
    },
    "patch_trpfd": "yes"
}`
```

**Comment by Cyberk999** [comment]
same issue

**Comment by XLuma** [comment]
use python 3.11, not 3.10 or 3.9. 

EDIT: The readme did indeed say 3.10 (although you are using 3.9 still). Readme  has been updated to reflect the correct python version needed.

**Comment by neonoafs** [comment]
> use python 3.11, not 3.10 or 3.9.
> 
> EDIT: The readme did indeed say 3.10 (although you are using 3.9 still). Readme has been updated to reflect the correct python version needed.

Thank you. It solved the problem.
