### ISSUE TITLE
randomize.bat gives "invalid syntax" error

### ISSUE THREAD

**Issue by rotteldastation** [XLuma/SV-Randomizer#3]
Sorry if this is a noob question. I've edited config.json and am now trying to run randomize.bat, and I get this error.
```
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Scarlet_Violet_Randomizer_1.1\Randomizer.py", line 3, in <module>
    import Randomizer.WildEncounters.wildrando as WildRandomizer
  File "C:\Users\user\Downloads\Scarlet_Violet_Randomizer_1.1\Randomizer\WildEncounters\wildrando.py", line 66
    match index:
          ^
SyntaxError: invalid syntax
Press any key to continue . . .
```
I have Python 3.11 installed and added to PATH, and the App Installer aliases disabled. What am I doing wrong here?

**Comment by XLuma** [comment]
use 3.10
